apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base
  - pod-monitor.yaml
  - scaled-object.yaml

patches:
  - path: deployment-patch.yaml
  - path: delete-cache-pvc.yaml
